In [1]:
Last login: Tue Aug 16 16:17:56 on ttys008

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) MacBook-Pro-14-inch-2077:~ himanshu$ pwd
/Users/himanshu
(base) MacBook-Pro-14-inch-2077:~ himanshu$ source ~/.bashrc 
[himanshu@MacBook-Pro-14-inch-2077 ~]$ cd bt2023_l4/
[himanshu@MacBook-Pro-14-inch-2077 bt2023_l4]$ ls
AADP_fjIqoUDoze-5tS0UJyka?dl=0
[himanshu@MacBook-Pro-14-inch-2077 bt2023_l4]$ python3
Python 3.9.13 (main, May 24 2022, 21:13:51) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.arrange(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'arrange'
>>> np.arrange(0,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'arrange'
>>> np.arange(2)
array([0, 1])
>>> clear
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'clear' is not defined
>>> 
>>> np.arange (3)
array([0, 1, 2])
>>> from pylab import genfromtxt
>>> data = genfromtxt ("medals.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1929, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: medals.txt not found.
>>> pwd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pwd' is not defined
>>> data = genfromtxt ("medals.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1929, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: medals.txt not found.
>>> data = genfromtxt ("medals.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1929, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: medals.txt not found.
>>> clear
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'clear' is not defined
>>> 
>>> data = genfromtxt ("medals.txt")
>>> dat [:,0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dat' is not defined
>>> data [:,0]
array([78., 44., 25., 16., 15.])
>>> data
array([[ 78.,  57.,  58., 193.],
       [ 44.,  44.,  44., 132.],
       [ 25.,  19.,  20.,  64.],
       [ 16.,  16.,  15.,  47.],
       [ 15.,  38.,  28.,  81.]])
>>> data [:,0]
array([78., 44., 25., 16., 15.])
>>> data [0,0]
78.0
>>> data [:,1]
array([57., 44., 19., 16., 38.])
>>> data [:,2]
array([58., 44., 20., 15., 28.])
>>> 
[himanshu@MacBook-Pro-14-inch-2077 bt2023_l4]$ c

[himanshu@MacBook-Pro-14-inch-2077 bt2023_l4]$ ls -ltr
total 75792
-rw-r--r--  1 himanshu  staff  38556405 Aug 16 16:27 AADP_fjIqoUDoze-5tS0UJyka?dl=0
-rw-r--r--@ 1 himanshu  staff        63 Aug 16 16:43 medals.txt
[himanshu@MacBook-Pro-14-inch-2077 bt2023_l4]$ pwd
/Users/himanshu/bt2023_l4
[himanshu@MacBook-Pro-14-inch-2077 bt2023_l4]$ cd ~/Dropbox/bt2023/l4/
[himanshu@MacBook-Pro-14-inch-2077 l4]$ vi bar_plot/
.ipynb_checkpoints/ bar.png             medals.txt
Untitled.ipynb      creat_bar_plot.py   
[himanshu@MacBook-Pro-14-inch-2077 l4]$ vi bar_plot/creat_bar_plot.py 












import numpy as np
import matplotlib.pyplot as plt
from pylab import genfromtxt


# creating the dataset
#data = np.loadtxt('medals.txt',dtype=str)
data = genfromtxt ("medals.txt")

# set width of bar
barWidth = 0.20

fig = plt.subplots(figsize =(12, 8))
fig,ax = plt.subplots()

# Set position of bar on X axis
br1 = np.arange(len(data[:,0]))
br2 = [x + barWidth for x in br1]
br3 = [x + barWidth for x in br2]

# Make the plot
plt.bar(br1, data [:,0], color ="C0", width = barWidth,
        edgecolor ='grey', label ='Gold')
plt.bar(br2, data[:,1], color ="C1", width = barWidth,
        edgecolor ='grey', label ='Silver')
plt.bar(br3, data[:,2], color ="C3", width = barWidth,
        edgecolor ='grey', label ="Bronze")
plt.xlabel('Country', fontweight ='bold', fontsize = 15)
plt.ylabel('No of Medals', fontweight ='bold', fontsize = 15)
plt.xticks([r + barWidth for r in range(len(data[:,0]))],
        ['Aus', 'Eng', 'Can', 'Ind', 'NZ'])
plt.grid(linestyle=":")
#ax.set_ylim(ymax= 100,ymin=0)
plt.legend()
##plt.tight_layout()
plt.savefig('bar.png', format='png',bbox_inches='tight',dpi=300)


SyntaxError: invalid syntax (3618023323.py, line 1)